#!/bin/bash
# Auto-generated by Lab Foundry - validate-lab
# Run after provisioning to verify lab health for zt-ans-bu-verify-sign

WEBHOOK_URL="${HEALTH_WEBHOOK_URL:-}"
LAB_NAME="zt-ans-bu-verify-sign"
GUID="${GUID:-unknown}"
RESULTS=()
FAILURES=0

check_http() {
    local name="$1" url="$2" expected_code="${3:-200}"
    local code
    code=$(curl -sk -o /dev/null -w '%{http_code}' --connect-timeout 15 --max-time 30 "$url" 2>/dev/null)
    if [ "$code" = "$expected_code" ]; then
        RESULTS+=("PASS: $name ($url) - HTTP $code")
    else
        RESULTS+=("FAIL: $name ($url) - expected $expected_code, got $code")
        ((FAILURES++))
    fi
}

check_http_auth() {
    local name="$1" url="$2" user="$3" pass="$4" expected_code="${5:-200}"
    local code
    code=$(curl -sk -o /dev/null -w '%{http_code}' --connect-timeout 15 --max-time 30 \
        -u "${user}:${pass}" "$url" 2>/dev/null)
    if [ "$code" = "$expected_code" ]; then
        RESULTS+=("PASS: $name ($url) - HTTP $code")
    else
        RESULTS+=("FAIL: $name ($url) - expected $expected_code, got $code")
        ((FAILURES++))
    fi
}

check_port() {
    local name="$1" host="$2" port="$3"
    if timeout 10 bash -c "echo >/dev/tcp/${host}/${port}" 2>/dev/null; then
        RESULTS+=("PASS: $name (${host}:${port}) - port open")
    else
        RESULTS+=("FAIL: $name (${host}:${port}) - port closed or unreachable")
        ((FAILURES++))
    fi
}

check_json_field() {
    local name="$1" url="$2" user="$3" pass="$4" jq_expr="$5" expected="$6"
    local actual
    actual=$(curl -sk --connect-timeout 15 --max-time 30 \
        -u "${user}:${pass}" "$url" 2>/dev/null | jq -r "${jq_expr}" 2>/dev/null)
    if [ "$actual" = "$expected" ]; then
        RESULTS+=("PASS: $name - ${jq_expr}=${actual}")
    else
        RESULTS+=("FAIL: $name - expected ${jq_expr}=${expected}, got=${actual}")
        ((FAILURES++))
    fi
}

AAP_HOST="${AAP_HOST:-https://control-${GUID}.${LAB_DOMAIN:-example.com}}"
GITEA_HOST="${GITEA_HOST:-https://gitea-${GUID}.${LAB_DOMAIN:-example.com}}"

# AAP Gateway / Automation Controller
check_http "AAP gateway" "${AAP_HOST}/" 200
check_http_auth "AAP API ping" "${AAP_HOST}/api/controller/v2/ping/" "admin" "ansible123!" 200
check_http_auth "AAP config" "${AAP_HOST}/api/controller/v2/config/" "admin" "ansible123!" 200

# Private Automation Hub (same gateway in AAP 2.5)
check_http_auth "PAH galaxy API" "${AAP_HOST}/api/galaxy/v3/namespaces/" "admin" "ansible123!" 200

# Gitea
check_http "Gitea UI" "${GITEA_HOST}/" 200
check_http "Gitea API" "${GITEA_HOST}/api/v1/repos/student/ansible-sign-demo" 200

# Gitea repo - ansible-sign-demo must exist
GITEA_REPO_STATUS=$(curl -sk --connect-timeout 15 "${GITEA_HOST}/api/v1/repos/student/ansible-sign-demo" 2>/dev/null | jq -r '.full_name' 2>/dev/null)
if [ "$GITEA_REPO_STATUS" = "student/ansible-sign-demo" ]; then
    RESULTS+=("PASS: Gitea repo student/ansible-sign-demo exists")
else
    RESULTS+=("FAIL: Gitea repo student/ansible-sign-demo not found (got: ${GITEA_REPO_STATUS})")
    ((FAILURES++))
fi

# ansible-sign installed on control node (check via SSH if BASTION_HOST is set)
if [ -n "${BASTION_HOST:-}" ] && [ -n "${BASTION_USER:-}" ]; then
    ANSIBLE_SIGN_VER=$(ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
        "${BASTION_USER}@${BASTION_HOST}" "ansible-sign --version 2>/dev/null" 2>/dev/null)
    if [ -n "$ANSIBLE_SIGN_VER" ]; then
        RESULTS+=("PASS: ansible-sign installed on control (${ANSIBLE_SIGN_VER})")
    else
        RESULTS+=("FAIL: ansible-sign not found on control node")
        ((FAILURES++))
    fi
fi

report_results() {
    local status="SUCCESS"
    [ "$FAILURES" -gt 0 ] && status="FAILED (${FAILURES} failure(s))"

    local report
    report="Lab Health Report: ${LAB_NAME} (GUID: ${GUID})\nStatus: ${status}\n"
    for r in "${RESULTS[@]}"; do
        report+="  ${r}\n"
    done

    echo -e "$report"

    if [ -n "$WEBHOOK_URL" ]; then
        local body
        body=$(printf '{"text":"%s","lab":"%s","guid":"%s","status":"%s","failures":%d}' \
            "$(echo -e "$report" | sed 's/"/\\"/g' | tr '\n' ' ')" \
            "$LAB_NAME" "$GUID" "$status" "$FAILURES")
        curl -s -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$body" 2>/dev/null
    fi
}

report_results
exit $FAILURES
